import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
 import Main from "./Main/main";
 import Headers from "./Header/headers";
import NavBar from "./NaviBar/nav";
 import Footers from "./Footer/footer";
import { Html } from "next/document";
 



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Appscrip-Nabakishore",
  description: "Generated by create next app",
};


export default function PageLayout(){
  return (
    <html lang="en">
    <body>

      <Headers/> 
      <NavBar/>
      <Main/>
      <Footers/>


    </body>
     </html>

 

  )
}

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body>
         
//         <Headers/>
//         <NavBar/>
//         <Main/>
//         <Footers/>        
//       </body>
//     </html>
//   );
// }
